
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or whichever branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js (if you need to build a JS app)
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # change this to the version you're using

    - name: Install dependencies
      run: npm install  # adjust to whatever package manager you're using

    - name: Build your project
      run: npm run build  # or your project's build command

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist  # adjust this to the directory where your build output is
